version: "2.21.0"
services:
  mysqldb:
    image: mysql:8
    container_name: mysql-service-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1002
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - shop_db_data:/var/lib/shop
    networks:
      - rest_network

  restservice:
    container_name: web-service
    restart: always
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/shop
    networks:
      - rest_network
volumes:
  shop_db_data:
networks:
  rest_network: